### ISSUE TITLE
Silence error `MultiSelect received no options`

### ISSUE THREAD

**Issue by abhijit-hota** [janosh/svelte-multiselect#107]
I'd like to know the design decision behind this to make this an error. I have valid use cases where I start out with an empty `MultiSelect` component and users are to add options to it.

The error should be a warning in my opinion.

Is there a way I can silence it?

**Comment by janosh** [comment]
Multiselect didn't originally have the ability for users to add custom options since I didn't have the tag input use case in mind when building it. Back then, a Multiselect with no options would have served no purpose so would have always been a developer error. Hence the current behavior to throw.

I agree that now with the option to set `allowUserOptions=true | 'append'`, always throwing an error no longer makes sense.

We should add a new prop

```js
onEmptyOptions: 'error' | 'warn' | 'ignore' = allowUserOptions ? 'warn' : 'error'
```

i.e. default to error only if users can't input custom options and otherwise warn the developer they might be creating an empty Multiselect inadvertently which they can then silence with `onEmptyOptions="ignore"` if appropriate.

**Comment by abhijit-hota** [comment]
Thanks for the clarification! That makes sense.

> We should add a new prop.

On second thought, I don't think a prop should be added at all. It's really a specific need and I'm fine with it just being a warning when user options are allowed. Polluting the prop namespace with specific props would just crowd the library unnecessarily.

**Comment by janosh** [comment]
I hadn't looked at this part of the code in a while. Just re-read it and actually, the behavior is already to only throw an error if `allowUserOptions` is `false`.

https://github.com/janosh/svelte-multiselect/blob/873fe7ee17a71ff1998a714347b1211dbd6f5673/src/lib/MultiSelect.svelte#L56-L63

Are you sure you saw that error even when `allowUserOptions=true | 'append'`? Closing this as the current behavior is already close to what I suggested above https://github.com/janosh/svelte-multiselect/issues/107#issuecomment-1248457797 without introducing a new prop.
