### ISSUE TITLE
View code examples on the website

### ISSUE THREAD

**Issue by Snailedlt** [janosh/svelte-multiselect#142]
Any chance we could view the code for all those examples on the website? 
Talking about these: https://svelte-multiselect.netlify.app/
![image](https://user-images.githubusercontent.com/43886029/199255273-efb7614b-f0c5-448e-b05a-81076601f3c8.png)

Maybe just an expandable view with highlighted code inside of it. Could also be a link to a jsfiddle or svelte repl, though inline code would be preferable.

Here's an example to showcase what it would look like: 
https://svelte-multiselect.w3spaces.com/svelte-multiselect-code-examples-icbl3.html
![image](https://user-images.githubusercontent.com/43886029/199260533-40d60fed-fb3f-4992-9de9-e0ee2d02b21f.png)

For syntax highlighting you could probably use [highlightjs](https://highlightjs.org/)

**Comment by janosh** [comment]
@Snailedlt I've been wanting to add that for a while. Never found a good way to both highlight code and render it on the page without duplicating it (which could lead to inconsistencies). There's a related issue over at https://github.com/pngwn/MDsveX/issues/52.

Would you like to submit a PR for this? Otherwise, you can of course view the code at https://github.com/janosh/svelte-multiselect/blob/main/src/components/Examples.svelte.

**Comment by janosh** [comment]
Ah one more thing. I'm familiar with highlight.js from https://github.com/janosh/tikz/blob/main/site/src/lib/CodeBlock.svelte where it works nicely. But IIRC, I tried https://github.com/AlexxNB/highlightjs-svelte/issues/7 but couldn't get it to highlight Svelte code. Simply highlighting as HTML would be fine for starters though.

**Comment by Snailedlt** [comment]
Wow, that was fast! 😁
Looks neat!
