### ISSUE TITLE
Website examples should be minimal reproducable examples

### ISSUE THREAD

**Issue by Snailedlt** [janosh/svelte-multiselect#145]
In order to understand the examples on the website more easily, each example should be a [minimal reproducable example](https://stackoverflow.com/help/minimal-reproducible-example). So if I copy the code into https://svelte.dev/repl the code should run right away. This would make it much easier for developers to implement the same functionality in their codebases.

Currently however, most of the code examples work with unknown factors such as custom components, svelte stores, etc...

Example: 
```js
<pre>bind:selected = {JSON.stringify($language_store)}</pre>

<label for="languages">Favorite programming languages?</label>

<MultiSelect
  id="languages"
  options={languages}
  placeholder="Take your pick..."
  bind:selected={$language_store}
>
  <LanguageSlot let:option {option} slot="selected" />
  <LanguageSlot let:option {option} slot="option" />
</MultiSelect>
```
Here the `<LanguageSlot>` is unknown. The content of `$language_store` is also unknown, and there's no import statement, so the code isn't a minimal reproducable example.

There's also examples that I couldn't get working at all when modifying them and adding them to a svelte repl. 
One of those is the [slots](https://svelte-multiselect.netlify.app/#slots) example , which I tried to reproduce in [this repl](https://svelte.dev/repl/6d00d5394b2643d1b4700e1cb51eeb73?version=3.52.0) , but the result was just a list with a bunch of undefined elements inside: 
![image](https://user-images.githubusercontent.com/43886029/199447364-532d1d92-8e88-4e7a-9c03-be47d808af79.png)

**Comment by janosh** [comment]
That's a great point! I liked the minimalism of only including the parts of the code that showed the mechanics, i.e. where to plug in slots, how to write the callbacks, etc. but that's probably because I wrote the code. I can see how someone who isn't familiar with the code base would prefer the complete runnable code. However, having multiple files to define the slot components in a slide out code fence isn't really feasible. So I added REPL links for each example in 
db42ac9. We could add Stackblitz links as well. Happy to take a PR if anyone feels so inclined.
