### ISSUE TITLE
keyboard rolling down doesn't role content

### ISSUE THREAD

**Issue by Avi-ADAM** [janosh/svelte-multiselect#15]

**Comment by janosh** [comment]
You mean this right? Thanks for raising the issue. Will take a look at this after closing #13.

https://user-images.githubusercontent.com/30958850/145533574-0d446c64-8f76-4f02-ba59-f1a6c027bf7b.mp4

**Comment by janosh** [comment]
This is fixed in [v3.0.0](https://www.npmjs.com/package/svelte-multiselect/v/3.0.0). Note that this major version comes with additional breaking changes documented in [this readme note](https://github.com/janosh/svelte-multiselect/tree/07fc3a626fd42a55d3f9d1b572e5fdbf59d25e9a#recent-breaking-changes).

The fix relies on the [`scrollIntoViewIfNeeded`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded) API which is not yet standardized yet has [surprisingly good browser support](https://caniuse.com/?search=scrollIntoViewIfNeeded) (currently at 93.45%).
