### ISSUE TITLE
Can not enter text in search on RELP's (or when implementing in my own app)

### ISSUE THREAD

**Issue by Dirk-tooth** [janosh/svelte-multiselect#188]
On your [demo site](https://multiselect.janosh.dev/#) the search feature works as expected, allowing users to type in the input field, searching through the options in the list. In the REPL's of the same examples and in my app (a direct copy and paste of the examples) the components do not allow users to type/search at all. 

(as of 12/28/22)
See a few examples of the current RELP's not working:
[example 1️⃣](https://svelte.dev/repl/79e22e1905c94456aa21564b4d5f8759?version=3.55.0)
[example 2️⃣](https://svelte.dev/repl/e3b88f59f62b498d943ecf7756ab75d7?version=3.55.0)

## Repro

See above ☝️ 

Steps to reproduce the problem (if needed to encounter error in StackBlitz):

1. Open [demo site](https://multiselect.janosh.dev/#) and try to type in the first example top search for more languages (working ✅)
2. Press the "REPL" button to go to [the REPL](https://svelte.dev/repl/e3b88f59f62b498d943ecf7756ab75d7?version=3.55.0) site
3. Try typing into the input on the right in the demo area to add more languages (not working ❌)

## Expected behavior

User should be able to type in the input to search the options to be added to the select/multi-select

## Additional context

I have also uncounted this issue when trying to implement in my own projects, not only on the RELP but my project is a very simple implementation copied from the RELP and from the demo site so I suspect the issues are related.

**Comment by janosh** [comment]
Ah crap. That's because the last CI release failed which @joelmukuthu alerted me to [yesterday](https://github.com/janosh/svelte-multiselect/pull/186#issuecomment-1365794676). So I made a local release and published that to NPM but forgot to stash some breaking local changes beforehand. In short, the v8.2.2 release is broken and should not be used. I deprecated it and made a new release [v8.2.3](https://github.com/janosh/svelte-multiselect/releases/tag/v8.2.3). Please try that.

**Comment by Dirk-tooth** [comment]
That seems to have worked, thanks for checking this out so quick! 10/10!!!
