### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by Snailedlt** [janosh/svelte-multiselect#228]
I'm getting a npm warning message when buiding a website that uses svelte-multiselect:
```sh
(!) Circular dependency
node_modules/svelte-multiselect/index.js -> node_modules/svesvelte-multiselect/MultiSelect.svelte -> node_modules/sve-multe-multiselect/index.js
```

No repro needed, just create a default svelte application, and build it with svelte-multiselect implemented.

Answer from Phind when asking why this warning occurs: https://www.phind.com/search?cache=e331e9aa-9101-4733-aedd-a26a613c0508

**Comment by janosh** [comment]
Yeah, I was aware of this. In many environments it still works which is why this didn't have high priority but I believe this is why the more recent versions of `svelte-multiselect` [don't work in the REPL](https://svelte.dev/repl/ea202bd627134d898802a11cfaf8ff0e).

![Screenshot 2023-05-15 at 07 54 27](https://github.com/janosh/svelte-multiselect/assets/30958850/8a6dcc5a-0de8-4eea-ad46-1500c3e1b46a)

Should be an easy fix with a bit of refactoring.

**Comment by Snailedlt** [comment]
Yeah, no biggie for us, just reported it since there wasn't an issue on it yet :)
If it fixes the REPL that would be very beneficial though.

Thanks for your continued great work!

**Comment by janosh** [comment]
v8.6.2 is out now. I was wrong about the REPL. The error is still there. Could you let me know if the NPM warning is gone?

**Comment by Snailedlt** [comment]
Great, will test it right away!

**Comment by Snailedlt** [comment]
@janosh The circular dependency is still there
```sh
(!) Circular dependency
node_modules/svelte-multiselect/dist/index.js -> node_modules/svelte-multiselect/dist/CmdPalette.svelte -> node_modules/svelte-multiselect/dist/index.js
```

**Comment by janosh** [comment]
Ah I forgot about `CmdPalette`. Will be fixed in the next release but maybe not worth it to do one just for that...

https://github.com/janosh/svelte-multiselect/blob/ebe5f6fa487676c7d36873dfbaef70047bb17f1b/src/lib/CmdPalette.svelte#L6

**Comment by Snailedlt** [comment]
No worries, and agreed 👍
