### ISSUE TITLE
If I set `readonly` true I can still use the multi select

### ISSUE THREAD

**Issue by frederikhors** [janosh/svelte-multiselect#45]
If I set `readonly` true I can still use the multi select.

**Comment by frederikhors** [comment]
I correct myself. I mean that the dropdown still comes out and I can write even if I can't select.

**Comment by janosh** [comment]
Yes, that was by design though I can see how that might not be the generally expected behavior in read-only mode.

Do you think it's worth having a third setting maybe called `readonly='no-select'` which behaves as `readonly=true` does currently and then the new `readonly=true` also disables dropdown and writing into input?

**Comment by frederikhors** [comment]
So I think we need `isDisabled` too.

**Comment by egdegauperaa** [comment]
@janosh @frederikhors I was just about to post a request for a prop called "disabled" :). And that it leads to the <select> getting a disabled attribute.

I don't think a readonly='no-select' is necessary. As a user I would just be confused and frustrated if I could open the list and look at the contents, but not being able to select something

**Comment by janosh** [comment]
@egdegauperaa So you're suggesting just renaming `readonly` to `disabled` and preventing the dropdown from opening in that state?

**Comment by egdegauperaa** [comment]
@janosh yes

**Comment by janosh** [comment]
@egdegauperaa I like that approach. #55 implements your suggestion.

**Comment by janosh** [comment]
Fix released in [v4.0.1](https://github.com/janosh/svelte-multiselect/releases/tag/v4.0.1).
